import os


class DefaultConfig:
    APPLICATION_ROOT = '/'
    RETURN_URL = 'https://localhost/sign/success'
    # Base URL should be different on production
    BASE_URL = os.getenv('DS_BASE_URL', 'https://demo.docusign.net/restapi')
    APP_URL = "http://localhost:8080"
    BASE_URI_SUFFIX = "/restapi"

    DS_TEMPLATE_ID = os.getenv('DS_TEMPLATE_ID')
    # The app's DocuSign integration key
    DS_CLIENT_ID = os.getenv('DS_CLIENT_ID')
    # Application secret
    DS_CLIENT_SECRET = os.getenv('DS_CLIENT_SECRET')
    DS_EXT_APP_USER_ID = os.getenv('DS_EXT_APP_USER_ID')
    DS_AUTHORIZATION_SERVER = os.getenv('DS_AUTHORIZATION_SERVER', 'account-d.docusign.com')
    # The id of the user.
    DS_IMPERSONATED_USER_ID = os.getenv('DS_IMPERSONATED_USER_ID')
    # RSA key generated by DocuSign platform
    PRIVATE_KEY_FILE = os.getenv('PRIVATE_KEY_FILE')
    SECRET_KEY = os.getenv('SECRET_KEY')
    SIGNING_URL_CALLBACK_ALLOWED_DOMAINS = os.getenv('SIGNING_URL_CALLBACK_ALLOWED_DOMAINS', 'http://localhost:8080')
    SIGNING_URL_CALLBACK_PATH = os.getenv('SIGNING_URL_CALLBACK_PATH', '')

    def __init__(self):
        urls = self.SIGNING_URL_CALLBACK_ALLOWED_DOMAINS.split(';')
        urls = [url.strip() for url in urls if url.strip()]
        self.SIGNING_URL_CALLBACK_ALLOWED_DOMAINS = urls


class ProductionConfig(DefaultConfig):
    DEBUG = False


class DevelopmentConfig(DefaultConfig):
    DEBUG = True


def get_config_object():
    if os.getenv('PRODUCTION_ENV') in ['True', 'true']:
        return 'config.ProductionConfig'
    return 'config.DevelopmentConfig'
